dist: xenial

services:
  - docker

branches:
  only:
    - master
    # Github release tags (for example "v0.9" or "v0.9.1").
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    # Branch names endings with "-release" (for example "0.9.0-release").
    - /-release$/

language: bash

env:
  global:
    - DOCKER_BUILDKIT=1
    - DOCKER_VER=5:18.09.5~3-0~ubuntu-xenial

# Install Docker 18.09+, which is necessary for experimental Dockerfile features.
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce=$DOCKER_VER
  - >
    sudo bash -c 'echo "{ \"experimental\": true, \"features\": { \"buildkit\": true } }" > /etc/docker/daemon.json'
  - sudo systemctl restart docker
  - docker version
  - docker info

script:
  - (cd dev && docker build -t exonum-env .)
  - (cd prod && docker build -t exonum-prod .)
  - cd tests && docker build -t example .
  - |
    docker run -d -p 8000:8000 --rm --name example example && \
      sleep 10 && \
      bash test.sh
