dist: trusty

services:
  - docker

branches:
  only:
    - master
    # Github release tags (for example "v0.9" or "v0.9.1").
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    # Branch names endings with "-release" (for example "0.9.0-release").
    - /-release$/

language: bash

script:
  - (cd dev && docker build -t exonum-env .)
  - (cd prod && docker build -t exonum-prod .)
  - cd tests && docker build -t example .
  - |
    docker run -d -p 8000:8000 --rm --name example example && \
      sleep 10 && \
      bash test.sh
